<table border="1">
    <thead>
        <tr>
            <th>項目</th>
            <th>登録内容</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>{{ConstParams::HOURLY_WAGE_JP}}</td>
            <td>{{$salary_data[ConstParams::HOURLY_WAGE]}}{{ConstParams::CURRENCY_JP}}</td>
        </tr>
        <tr>
            <td>{{ConstParams::CREATED_AT_JP}}</td>
            <td>{{$salary_data[ConstParams::CREATED_AT]}}</td>
        </tr>
        <tr>
            <td>{{ConstParams::UPDATED_AT_JP}}</td>
            <td>{{$salary_data[ConstParams::UPDATED_AT]}}</td>
        </tr>
        <tr>
            <td>{{ConstParams::CREATED_BY_JP}}</td>
            <td>{{$salary_data[ConstParams::CREATED_BY]}}</td>
        </tr>
        <tr>
            <td>{{ConstParams::UPDATED_BY_JP}}</td>
            <td>{{$salary_data[ConstParams::UPDATED_BY]}}</td>
        </tr>
    </tbody>
</table>