<table border="1">
    <thead>
        <tr>
            <th>項目</th>
            <th>登録内容</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>{{ConstParams::USER_ID_JP}}</td>
            <td>{{$user_data[ConstParams::USER_ID]}}</td>
        </tr>
        <tr>
            <td>{{ConstParams::KANJI_LAST_NAME_JP}}</td>
            <td>{{$user_data[ConstParams::KANJI_LAST_NAME]}}</td>
        </tr>
        <tr>
            <td>{{ConstParams::KANJI_FIRST_NAME_JP}}</td>
            <td>{{$user_data[ConstParams::KANJI_FIRST_NAME]}}</td>
        </tr>
        <tr>
            <td>{{ConstParams::KANA_LAST_NAME_JP}}</td>
            <td>{{$user_data[ConstParams::KANA_LAST_NAME]}}</td>
        </tr>
        <tr>
            <td>{{ConstParams::KANA_FIRST_NAME_JP}}</td>
            <td>{{$user_data[ConstParams::KANA_FIRST_NAME]}}</td>
        </tr>
        <tr>
            <td>{{ConstParams::EMAIL_JP}}</td>
            <td>{{$user_data[ConstParams::EMAIL]}}</td>
        </tr>
        <tr>
            <td>{{ConstParams::EMAIL_VERIFIED_AT_JP}}</td>
            <td>{{$user_data[ConstParams::EMAIL_VERIFIED_AT]}}</td>
        </tr>
        <tr>
            <td>{{ConstParams::LOGIN_ID_JP}}</td>
            <td>{{$user_data[ConstParams::LOGIN_ID]}}</td>
        </tr>
        <tr>
            <td>{{ConstParams::CREATED_AT_JP}}</td>
            <td>{{$user_data[ConstParams::CREATED_AT]}}</td>
        </tr>
        <tr>
            <td>{{ConstParams::UPDATED_AT_JP}}</td>
            <td>{{$user_data[ConstParams::UPDATED_AT]}}</td>
        </tr>
        <tr>
            <td>{{ConstParams::CREATED_BY_JP}}</td>
            <td>{{$user_data[ConstParams::CREATED_BY]}}</td>
        </tr>
        <tr>
            <td>{{ConstParams::UPDATED_BY_JP}}</td>
            <td>{{$user_data[ConstParams::UPDATED_BY]}}</td>
        </tr>
    </tbody>
</table>